name: "Nginx Deployment"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  terrafom:
    runs-on: ubuntu-latest
    

    steps:
      - name: Docker Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-assignment .
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-assignment

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        env:
          TF_VAR_private_key: ${{ secrets.AWS_KEYPAIR }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: terraform plan -no-color

      - name: SSH to AWS Instance and Pull Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEYPAIR }}
          script: |
            sudo docker run -d -p 80:80 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/nginx-assignment
