name: "Terraform destroy"
on:
  workflow_dispatch: 


jobs:
  terrafom:
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get MY IP
        id: get_my_ip
        run: echo "::set-output name=my_ip::$(curl https://ipv4.icanhazip.com/)"

      - name: Terraform Init
        run: terraform init

      - name: Terraform destroy 
        env:
          TF_VAR_private_key: ${{ secrets.AWS_KEYPAIR }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_my_ip: ${{ steps.get_my_ip.outputs.my_ip }}

        run: terraform destroy -auto-approve
